### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by srnyx** [nulli0n/GoldenChallenges#3]
Running Paper-Spigot 1.16.5
https://pastebin.com/1VVkLtc4

**Comment by nulli0n** [comment]
Use both .jar

**Comment by srnyx** [comment]
> Use both .jar

Huh? If you're talking about NexEngine then yes I have that installed already.

**Comment by srnyx** [comment]
Seems to not be happening anymore, very strange.
It may have been a database issue but that wouldn't make sense.
